import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const latoFont = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--lato-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${latoFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
